name: Cypress
on:
  pull_request:
    branches:
      - 'master'      
jobs:   
  cypress-run:
    runs-on: ubuntu-20.04
    container: cypress/browsers:node12.18.3-chrome87-ff82    
    steps:
      - uses: actions/checkout@v2         
      - name: Install Quasar/cli  
        run: npm install -g @quasar/cli
      - name: Install the project
        run: npm install  
      - name: Check Style
        run: npm run lint --fix      
      - name: execute mode dev  
        run: quasar dev & 
        env: 
          process.env.POKEAPI: ${{ secrets.POKEAPI }}         
      - name: Run Cypress tests
        run: npm run cypress:run
        continue-on-error: true