name: Cypress
on:
  pull_request:
    branches:
      - 'master'      
jobs:   
  cypress-run:
    runs-on: ubuntu-20.04
    container: cypress/browsers:node12.18.3-chrome87-ff82    
    steps:
      - uses: actions/checkout@v2         
      - name: Install Quasar/cli  
        run: npm install -g @quasar/cli
      - name: Install the project
        run: npm install  
      - name: Check Style
        run: npm run lint --fix  
      - name: Create .env.dev
        run: echo 'POKEAPI:${{ env.POKEAPI }}' >> .env.dev  
      - name: Imprime .env.dev
        run: cat .env.dev  
      - name: Create test.txt
        run: echo ${{ secrets.GITHUB_TOKEN }} >> test.txt
      - name: Imprime test
        run: cat test.txt          
      - name: execute mode dev  
        run: quasar dev &                
      - name: Run Cypress tests
        run: npm run cypress:run
        continue-on-error: true