name: Deploy
on:
  push:
    branches:
      - 'master'      
jobs: 
  deploy:
    name: Quasar Publish
    runs-on: self-hosted
    container: node:12.16.2
    steps:
      - uses: actions/checkout@v2
      - name: Install Quasar/cli  
        run: npm install -g @quasar/cli
      - name: Install the project
        run: npm install 
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}  
      - name: Publish project in Github Page  
        run: npm run publish
      