name: Deploy
on:
  push:
    branches:
      - 'master'      
jobs: 
  deploy:
    name: Quasar Publish
    runs-on: self-hosted
    container: node:12.16.2
    steps:
      - uses: actions/checkout@v2
      - name: Install Quasar/cli  
        run: npm install -g @quasar/cli
      - name: Install project
        run: npm install 
      - name: Build project
        run: quasar build   
      - name: Publish project  
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: rogerbaracy.s@gmail.com
          build_dir: dist/spa
      