name: Deploy Automatic
on:
  push:
    branches:
      - 'master'
jobs:  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Deploy project
        run: npm run publish
  cypress-e2e-chrome81:
    name: Test in prod
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.16.2-chrome81-ff75
    steps:
      - uses: actions/checkout@v2
      - name: Install a project with a clean slate
        run: |
          npm ci
          $(npm bin)/cypress cache path
          $(npm bin)/cypress cache list
          $(npm bin)/cypress verify
      - name: Run Cypress tests
        run: npm run test:chrome
        continue-on-error: true     