name: Deploy
on:
  push:
    branches:
      - 'master'      
jobs: 
  deploy:
    name: Quasar Publish
    runs-on: self-hosted
    container: node:12.16.2
    steps:
      - uses: actions/checkout@v2
      - name: Install Quasar/cli  
        run: npm install -g @quasar/cli
      - name: Install the project
        run: npm install  
      - name: Set Creds
        run: git config user.name rogerbaracy && git config user.email rogerbaracy.s@gmail.com     
      - name: Publish project in Github Page  
        run: npm run deploy